### ISSUE TITLE
pandas support

### ISSUE THREAD

**Issue by onsimon** [JoelRoxell/borsdata-sdk#13]
Hey Joel, really nice client/sdk here. I was thinking about creating something similar earlier although primarily with pandas DataFrames result sets. Could be implemented as a method kwarg here I guess. I think it would be super valuable as most python users will be using pandas with the API anyway. 

Or if this lib should be kept with minimal dependencies then maybe a pandas wrapper lib for this. What do you think?

**Comment by JoelRoxell** [comment]
Could you give an example of how you'd like a method signature to look like in this case? The dependency size isn't' a problem atm; in either case, one will almost always translate the fetched data to a `DataFrame` later on.
