### ISSUE TITLE
There is not start and end params in the /api/v{version}/instruments API

### ISSUE THREAD

**Issue by buggfabriken** [JoelRoxell/borsdata-sdk#17]
The API seems to set it, but from the swagger it does not seem to be an available parameter.

https://github.com/JoelRoxell/borsdata-sdk/blob/0fe982929f97fc363b8208f98f15b0d7043784ca/borsdata_sdk/BorsdataAPI.py#L137

Swagger: https://apidoc.borsdata.se/swagger/index.html

**Comment by JoelRoxell** [comment]
![image](https://user-images.githubusercontent.com/15216051/115680014-77a75480-a353-11eb-940d-7dc9d8d7d79c.png)

`from` & `to` is available.
