### ISSUE TITLE
Please add support for 20 years history

### ISSUE THREAD

**Issue by locupleto** [JoelRoxell/borsdata-sdk#18]
Please add support for 20 years history recently available in the API. See [APIUpdate](https://github.com/Borsdata-Sweden/API/wiki/20-year-history?utm_campaign=cmp_1647323&utm_medium=email&utm_source=getanewsletter)

Probably a very minor change. I tested by adding the line
`            params.update({'maxcount': 20})`
at line 138 to update the get_instrument_stock_price method for instance and that seemed to do the trick for that method.

**Comment by JoelRoxell** [comment]
Long "leave of absence", I'll review the entire library this weekend and see what should be updated.

**Comment by JoelRoxell** [comment]
Should suffice https://github.com/JoelRoxell/borsdata-sdk/blob/master/borsdata_sdk/BorsdataAPI.py#L182 ?

`pip instrall borsdata-sdk 1.1.3`

**Comment by locupleto** [comment]
Yep, sweet - thanx!
